const schema = {
  users: {
    id: "string",
    role: "student | parent | teacher | admin",
    email: "string",
    passwordHash: "string",
    displayName: "string",
    createdAt: "ISODate",
  },
  students: {
    id: "string",
    userId: "string",
    admissionNo: "string",
    firstName: "string",
    lastName: "string",
    classId: "string",
    parentIds: "string[]",
    accessPin: "string",
    status: "active | pending | inactive",
  },
  parents: {
    id: "string",
    userId: "string",
    firstName: "string",
    lastName: "string",
    studentIds: "string[]",
    phone: "string",
  },
  teachers: {
    id: "string",
    userId: "string",
    firstName: "string",
    lastName: "string",
    department: "string",
    classIds: "string[]",
    status: "active | leave | inactive",
  },
  classes: {
    id: "string",
    name: "string",
    section: "nursery | primary | secondary",
    classTeacherId: "string",
  },
  subjects: {
    id: "string",
    code: "string",
    name: "string",
    section: "nursery | primary | secondary",
  },
  terms: {
    id: "string",
    name: "string",
    sessionName: "string",
    startDate: "ISODate",
    endDate: "ISODate",
    isCurrent: "boolean",
  },
  timetableEntries: {
    id: "string",
    classId: "string",
    day: "string",
    time: "string",
    subjectId: "string",
    teacherId: "string",
  },
  results: {
    id: "string",
    studentId: "string",
    subjectId: "string",
    termId: "string",
    score: "number",
    grade: "string",
    teacherId: "string",
    publishedAt: "ISODate | null",
  },
  attendance: {
    id: "string",
    studentId: "string",
    classId: "string",
    date: "ISODate",
    status: "present | absent | late",
    markedBy: "string",
  },
  assignments: {
    id: "string",
    title: "string",
    description: "string",
    classId: "string",
    subjectId: "string",
    teacherId: "string",
    dueDate: "ISODate",
    createdAt: "ISODate",
  },
  fees: {
    id: "string",
    studentId: "string",
    termId: "string",
    item: "string",
    amountDue: "number",
    amountPaid: "number",
    provider: "paystack | stripe | manual",
    status: "paid | partially_paid | unpaid",
  },
  paymentTransactions: {
    id: "string",
    feeId: "string",
    provider: "paystack | stripe",
    reference: "string",
    amount: "number",
    status: "initialized | success | failed",
    checkoutUrl: "string",
  },
  announcements: {
    id: "string",
    title: "string",
    message: "string",
    audience: "all | students | parents | teachers | admins",
    authorUserId: "string",
    createdAt: "ISODate",
  },
  admissions: {
    id: "string",
    childName: "string",
    age: "number",
    programme: "string",
    parentName: "string",
    email: "string",
    phone: "string",
    notes: "string",
    status: "new | under_review | interview_scheduled | offer_sent",
    createdAt: "ISODate",
    enrolledStudentId: "string | null",
    enrolledParentId: "string | null",
    enrolledAt: "ISODate | null",
  },
  contactInquiries: {
    id: "string",
    name: "string",
    email: "string",
    subject: "string",
    message: "string",
    status: "new | read | responded",
    createdAt: "ISODate",
  },
  reportCards: {
    id: "string",
    studentId: "string",
    termId: "string",
    teacherComment: "string",
    principalComment: "string",
    generatedAt: "ISODate",
    downloadUrl: "string | null",
  },
  teacherMessages: {
    id: "string",
    teacherId: "string",
    parentId: "string",
    studentId: "string",
    subject: "string",
    message: "string",
    createdAt: "ISODate",
  },
  sessions: {
    id: "string",
    token: "string",
    userId: "string",
    role: "student | parent | teacher | admin",
    createdAt: "ISODate",
    expiresAt: "ISODate",
  },
  passwordResetTokens: {
    id: "string",
    userId: "string",
    role: "student | parent",
    email: "string",
    code: "string",
    createdAt: "ISODate",
    expiresAt: "ISODate",
    usedAt: "ISODate | null",
  },
  portalInvitations: {
    id: "string",
    targetType: "student | parent",
    targetId: "string",
    email: "string",
    status: "sent | delivered_demo",
    activationUrl: "string",
    invitationCode: "string",
    sentAt: "ISODate",
  },
  auditLogs: {
    id: "string",
    actorUserId: "string",
    actorName: "string",
    action: "string",
    resourceType: "string",
    resourceId: "string",
    detail: "string",
    createdAt: "ISODate",
  },
  notificationLogs: {
    id: "string",
    role: "student | parent | teacher | admin",
    channel: "email | demo | portal",
    delivery: "email | demo | queued",
    recipientEmail: "string",
    subject: "string",
    eventType: "portal_invite | password_reset | announcement",
    detail: "string",
    createdAt: "ISODate",
  },
};

module.exports = { schema };
